sudo: false
cache: bundler
language: ruby
matrix:
  include:
     - rvm: 2.0.0
     - rvm: 2.1.10
     - rvm: 2.2.5
     - rvm: 2.3.1
     - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rspec spec
