sudo: false
cache: bundler
language: ruby
matrix:
  include:
     - rvm: 2.0.0
       env: RUBY='2.0'
     - rvm: 2.1.10
       env: RUBY='2.1'
     - rvm: 2.2.5
       env: RUBY='2.2'
     - rvm: 2.3.1
       env: RUBY='2.3'
     - rvm: ruby-head
       env: RUBY='2.4'
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rspec spec
